import aceituna from "../assets/plantsimages/aceituna.png";
import agraz from "../assets/plantsimages/agraz.png";
import aguacate from "../assets/plantsimages/aguacate.png";
import albaricoque from "../assets/plantsimages/albaricoque.png";
import almendra from "../assets/plantsimages/almendra.png"; 
import araza from "../assets/plantsimages/araza.png";
import arandano from "../assets/plantsimages/arandano.png";
import banano from "../assets/plantsimages/banano.png";
import borojo from "../assets/plantsimages/borojo.png";
import cacao from "../assets/plantsimages/cacao.png";
import frutales from "../assets/plantsimages/fresa.png";

export const frutas = [
  {
    nombre: "aceituna",
    descripcion:
      "El olivo es un árbol que puede alcanzar hasta siete metros de altura, presenta un tronco grueso, con numerosos nudos y de corteza color pardo grisácea, sus hojas son perennes con forma lanceolada,sus flores son hermafroditas y su fruto es la aceituna de cuyo zumo se obtiene el aceite. El cultivo de olivo crece en suelos con buen drenaje, ricos en materia orgánica y pH neutro ",
    cientifico: "Olea europaea",
    cultivo: frutales,
    Tipo_cultivo:  "Frutal",
    Germina: "28 días ",
    cosechar: "61 meses y 3 semanas ",
    temporada: "Otoño",
    maceta:"10litros",
    tierrra:"42 días después de sembrar ",
    piso:"Clima cálido",
    temp_max:"27°C",
    temp_min:"20°C ",
    riego:"Poca o cada5 dias",
    solar:"Bastante luz",
    altura:"7 metros",
    profundidad:"8 centímetros",
    separacion:"60 centímetros",
    tipo_suelo:"Francos",
    ph:"Neutro (6.6 - 7.3)",
    luna:"Menguante ",
    imagen: aceituna,
  },
  {
    nombre: "agraz",
    descripcion: "Este fruto del genero vaciium, como lo inidca su nombre cientifico, es una planta  que crece entre 2.00 y 3.000 metros  ",
    cientifico: "Vaccinium meridionale",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: "25 días ",
    cosechar: "6 meses ",
    temporada: "invierno",
    maceta:"20 litros",
    tierrra:"49 dias despues de sembrar",
    piso:"Clima tenplado",
    temp_max:"16°C",
    temp_min:"8°C",
    riego:"Abundante todos los dias",
    solar:"Bastante luz solar",
    altura:"7 metros",
    profundidad:"2 centrimetros",
    separacion:"70 centrimetros",
    tipo_suelo:"Francos",
    ph:"Acido(3.5-6.5)",
    luna:"Menguante",
    imagen: agraz,
  },
  {
    nombre: "aguacate",
    descripcion: "Es una especie arborea del genero Persea perteneciente a la familia Lauraceae, son arboles de hojas pernnes,alternas y multiformes, se plantan a principios de la primavera en climas templados, se adpata a temperaturas entrelos 17 y 24° C siendo las codiciones idelaes para su desarrollo, sus flores son pequeñas y estas suelen aparecer a finales de invierno. El agaucate es rico en vitaminas y minerales.",
    cientifico: "Persea americana",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: "30 días ",
    cosechar: "61 meses y 3 semanas ",
    temporada: "Primavera",
    maceta:"20 litros",
    tierrra:"120 dias despues de sembrar",
    piso:"Clima tenplado",
    temp_max:"24°C",
    temp_min:"17°C",
    riego:"Regular o cada 3 dias",
    solar:"Bastante luz solar",
    altura:"5 metros",
    profundidad:"5 centrimetros",
    separacion:"5 metros",
    tipo_suelo:"Limoso",
    ph:"Neutro(6.6-7.3)",
    luna:"Nueva",
    imagen: aguacate,
  },
  {
    nombre: "albaricoque",
    descripcion: "El albaricoque crece en arboles robustos de copa desarrollada, es sumamente resistente a las ssequias pero mu sensible a las heladas.El albaricoque debe ser recogido en plena madurez ya que de lo contrario la pulpa no desarrolla su sabor dulce y el fruto se tornara incomestible para el consumidor.Se caracteriza por ser un fruto similar al melocoton y el durazno, pero es mas pequeño, de color amarillo palido o anaranjado con alguna sombra roja, su pulpa no es jugosa,tiene textura fibrosa y consistencia harinosa  ",
    cientifico: "Prunus armeniaca",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: " 32 dias",
    cosechar: "73 meses",
    temporada: "Privamavera",
    maceta:"20 Litros",
    tierrra:"65 dias despues de sembrar",
    piso:"Clima templado",
    temp_max:"28 °C",
    temp_min:"15 °C",
    riego:"Abundante o todos los dias",
    solar:"Abundante Luz ",
    altura:"4 metros",
    profundidad:"10 centimetros",
    separacion:"2.5 metros",
    tipo_suelo:"Salino",
    ph:"Acido (3.5 - 6.5)",
    luna:"Llena",
    imagen: albaricoque,
  },
  {
    nombre: "almendra",
    descripcion: "Almendro pertence a la familia Rosceae es una especie que se ubica siempre en zonas exteriores. Se caracteriza porque en su edad adulta cuenta con un tronco marron de corteza agrietada,puede alcanzar entre tres y seis metros de altura,sus hojas son laceoladas,largas estrechas y puntiagudas, sus flores presentas tonos blancos o rosados de las cuales saldran los frutos semillas.El almendroes un arbol muy resistente y no reuqiere de mucho cuidado para crecer,crece bien en climas calidos, no tolera el frio ni las heladas y puede resistir periodos de sequia.",
    cientifico: "Prunus dulcis",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: "15 dias ",
    cosechar: "61 meses y 3 semanas",
    temporada: "Primavera",
    maceta:"20 Litros",
    tierrra:"35 dias despues de sembarar",
    piso:"Clima calido",
    temp_max:"20 °C",
    temp_min:"15 °C",
    riego:"Regular o cada 3 dias",
    solar:"Luz moderada",
    altura:"6 metros",
    profundidad:"15 centimetros",
    separacion:"1.5 metros",
    tipo_suelo:"Francos",
    ph:"Neutro",
    luna:"Menguante",
    imagen: almendra,
  },
  {
    nombre: "araza",
    descripcion: "El araza se conoce tambien como guayaba amazonica, es un arbusto de hasta 3 metros de altura con ramificacion densa, se adapta muy bien a los suelos pobres y acidos, sin embargo prefiere los suelos con buena materia organica y buen drenaje; se caracteriza por ser sensible al frio.",
    cientifico: "Eugenia stipitata",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: "20 dias",
    cosechar: "6 meses y 2 semanas",
    temporada: "Otoño",
    maceta:"20 Litros",
    tierrra:"40 dias despues de sembrar",
    piso:"Clima calido",
    temp_max:"26 °C",
    temp_min:"19 °C",
    riego:"Regular o cada 3 dias",
    solar:"Luz moderda",
    altura:"2.5 metros",
    profundidad:"15 centimetros",
    separacion:"80 centimretos",
    tipo_suelo:"Francos",
    ph:"Acido",
    luna:"Creciente",
    imagen: araza,
  },
  {
    nombre: "arándano",
    descripcion: "El arándano es un arbusto que prefiere suelos ácidos con buen drenaje y mucha materia orgánica. Es sensible a la sequía, por lo que necesita riego regular, pero sin encharcamientos. Idealmente, se cultiva en zonas con inviernos fríos, ya que requiere de horas de frío para producir frutos de calidad. Se puede cultivar tanto en el suelo como en macetas grandes con un pH de entre 4.5 y 5.5. Los arándanos son valorados por sus propiedades antioxidantes.",
    cientifico: "Vaccinium corymbosum",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: "30-60 días",
    cosechar: "3-4 años",
    temporada: "Primavera-verano",
    maceta: "20-30 litros",
    tierrra: "Ácida, bien drenada",
    piso: "Clima templado-frío",
    temp_max: "25°C",
    temp_min: "-5°C",
    riego: "Poca o cada 5 dias",
    solar: "Pleno sol",
    altura: "1-1.5 metros",
    profundidad: "1 cm",
    separacion: "1-1.5 metros",
    tipo_suelo: "Salino",
    ph: "Acido (4.5-5.5)",
    luna: "Creciente",
    imagen: arandano,
  },
  {
    nombre: "banano",
    descripcion: "El banano es una planta tropical que requiere temperaturas cálidas y alta humedad para crecer de manera óptima. Se cultiva mejor en suelos ricos en materia orgánica, profundos y bien drenados. Requiere riego abundante y constante, especialmente en épocas de sequía. Es sensible a los vientos fuertes, por lo que se recomienda protegerlo o plantarlo en zonas resguardadas. Los bananos suelen cosecharse a los 9-12 meses después de la plantación.",
    cientifico: "Musa paradisiaca",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: "2-3 semanas",
    cosechar: "9-12 meses",
    temporada: "Todo el año en climas tropicales",
    maceta: "20 litros",
    tierrra: "No,debido ala delicadeza del cultivo",
    piso: "Clima cálido",
    temp_max: "35°C",
    temp_min: "15°C",
    riego: "POca o cada 5 dias",
    solar: "Pleno sol",
    altura: "2-4 metros",
    profundidad: "10-15 cm",
    separacion: "2-3 metros",
    tipo_suelo: "Arenoso",
    ph: "Neutro (6-7)",
    luna: "Creciente",
    imagen: banano,
  },
  {
    nombre: "borojó",
    descripcion: "El borojó es un árbol de crecimiento lento, típico de las zonas tropicales húmedas. Prefiere suelos ricos en materia orgánica y con buen drenaje. Necesita alta humedad y sombra parcial en las primeras etapas de su crecimiento. El riego debe ser constante, sin dejar que la tierra se seque completamente. Esta planta es muy apreciada por su fruto rico en nutrientes y es utilizado en preparaciones alimenticias y medicinales.",
    cientifico: "Borojoa patinoi",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: "30-40 días",
    cosechar: "52 meses y 3 semanas",
    temporada: "Todo el año en clima tropical",
    maceta: "15 Litros",
    tierrra: "70 dias despues de sembrar",
    piso: "Clima tropical húmedo",
    temp_max: "30°C",
    temp_min: "20°C",
    riego: "Regular o cada 3 dias",
    solar: "Bastante luz",
    altura: "5-7 metros",
    profundidad: "15-20 cm",
    separacion: "3-4 metros",
    tipo_suelo: "Salino",
    ph: "Acido (5-6)",
    luna: "Creciente",
    imagen: borojo,
  },
  {
    nombre: "cacao",
    descripcion: "El cacao es una planta que prospera en climas cálidos y húmedos. Prefiere suelos bien drenados, ricos en materia orgánica y con un pH ligeramente ácido. Requiere sombra parcial, especialmente en las primeras etapas de su desarrollo. Necesita riego constante, pero evitando el encharcamiento. El cacao es sensible a los cambios bruscos de temperatura y se cultiva mejor en zonas protegidas del viento.",
    cientifico: "Theobroma cacao",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: "10 dias",
    cosechar: "49 meses y 3 semanas",
    temporada: "Todo el año en climas tropicales",
    maceta: "20 Litros",
    tierrra: "60 dias despues de sembrar",
    piso: "Clima tropical",
    temp_max: "30°C",
    temp_min: "20°C",
    riego: "Regular o cada 3 dias",
    solar: "Sombra parcial",
    altura: "4-8 metros",
    profundidad: "10-15 cm",
    separacion: "3-4 metros",
    tipo_suelo: "Franco,",
    ph: "Neutro (5.5-6.5)",
    luna: "Menguante",
    imagen: cacao,
  },
  
];
