import aceituna from "../assets/plantsimages/aceituna.png";
import agraz from "../assets/plantsimages/agraz.png";
import frutales from "../assets/plantsimages/fresa.png";

export const frutas = [
  {
    nombre: "aceituna",
    descripcion:
      "El olivo es un árbol que puede alcanzar hasta siete metros de altura, presenta un tronco grueso, con numerosos nudos y de corteza color pardo grisácea, sus hojas son perennes con forma lanceolada,sus flores son hermafroditas y su fruto es la aceituna de cuyo zumo se obtiene el aceite. El cultivo de olivo crece en suelos con buen drenaje, ricos en materia orgánica y pH neutro ",
    cientifico: "Olea europaea",
    cultivo: frutales,
    Tipo_cultivo:  "Frutal",
    Germina: "28 días ",
    cosechar: "61 meses y 3 semanas ",
    temporada: "Otoño",
    maceta:"10litros",
    tierrra:"42 días después de sembrar ",
    piso:"Clima cálido",
    temp_max:"27°C",
    temp_min:"20°C ",
    riego:"Poca o cada5 dias",
    solar:"Bastante luz",
    altura:"7 metros",
    profundidad:"8 centímetros",
    separacion:"60 centímetros",
    tipo_suelo:"Francos",
    ph:"Neutro (6.6 - 7.3)",
    luna:"Menguante ",
    imagen: aceituna,
  },
  {
    nombre: "agraz",
    descripcion: "Este fruto del genero vaciium, como lo inidca su nombre cientifico, es una planta  que crece entre 2.00 y 3.000 metros  ",
    cientifico: "Vaccinium meridionale",
    cultivo: frutales,
    Tipo_cultivo: "Frutal",
    Germina: "25 días ",
    cosechar: "6 meses ",
    temporada: "invierno",
    maceta:"20 litros",
    tierrra:"49 dias despues de sembrar",
    piso:"clima tenplado",
    temp_max:"16°C",
    temp_min:"8°C",
    riego:"Abundante todos los dias",
    solar:"Bastante luz solar",
    altura:"7 metros",
    profundidad:"2 centrimetros",
    eparacion:"70 centrimetros",
    tipo_suelo:"Francos",
    ph:"Acido(3.5-6.5)",
    luna:"Menguante",
    imagen: agraz,
  },
];
